# Generated by Django 4.2.23 on 2026-02-08 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ファイル名')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='csvファイル')),
                ('learned_model', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='学習済みモデル')),
            ],
        ),
    ]
