# Generated by Django 4.2.23 on 2026-02-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserID',
            new_name='Files',
        ),
    ]
