# Generated by Django 4.2.23 on 2026-02-08 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0002_rename_userid_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ファイル名')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='csvファイル')),
                ('input_size', models.IntegerField(verbose_name='入力の数')),
                ('learned_model', models.IntegerField(verbose_name='出力の数')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
