# Generated by Django 4.2.23 on 2026-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_file_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='output_size',
            field=models.IntegerField(default=0, verbose_name='出力の数'),
        ),
        migrations.AlterField(
            model_name='file',
            name='input_size',
            field=models.IntegerField(default=0, verbose_name='入力の数'),
        ),
        migrations.AlterField(
            model_name='file',
            name='learned_model',
            field=models.IntegerField(verbose_name='学習済みモデル'),
        ),
    ]
