# Generated by Django 4.2.23 on 2026-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0004_file_output_size_alter_file_input_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='learned_model',
            field=models.IntegerField(null=True, verbose_name='学習済みモデル'),
        ),
    ]
