# Generated by Django 4.2.23 on 2026-02-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0005_alter_file_learned_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='learned_model',
            field=models.FileField(null=True, upload_to='files/', verbose_name='学習済みモデル'),
        ),
    ]
